controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_logout:
    path: /logout
    methods: GET

# app_verify_email:
#     path: /verification-email/
#     controller: App\Security\EmailVerifier::handleEmailConfirmation
